# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2be2b7ba23c8a6489b76f617a56aa44f41344538f06d6a5fd51116f8ef43d1e94db47d84e929452c073eab4ab1de2a692e00037226436b9c485f1db2b57d9e6

test:
  secret_key_base: 646902194fad508474fea9dcce6c6aa25e232e2dd8e5ae65eb105de82f8125de9a85dabc21504c35e0788ebf5e22d567cf9af6504823ab7d209c3d16ab18deb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
